### ISSUE TITLE
Blendercam and Blender 2.8x

### ISSUE THREAD

**Issue by Silventar** [blendercam/blendercam#7]
Good morning!

I know Blendercam does not work with Blender 2.8 and higher. What would it take to make it work? I would donate funds and I believe I could help get funds raised if needed. Or is it just to massive of a task at this point?

Endercam seems like it would be perfect for the hobbiest, especially since you have been committed to keeping it free and open source. And the fact that blender users do not HAVE to learn a new tool to get into cnc would be great... Please consider starting back up on this! 

I'm not a coder, but I would love to help. I can test, document, promote...

**Comment by TurBoss** [comment]
hello, 
belndercam master was ported to 2.8 months ago only exaustive test is needed
so maybe some parts doesn't work

**Comment by TurBoss** [comment]
follow this docs to install master for 2.80

**Comment by TurBoss** [comment]
https://github.com/vilemduha/blendercam/wiki/Using-Blendercam-from-github

**Comment by Silventar** [comment]
Yesyayyes! Thank you so much! I'll check it out
